[names.maps]
test-map-1 = "Test Map 1"
test-map-2 = "Test Map 2"
test-map-3 = "Test Map 3"
test-pc = "Test PC"

[names.bag]
favorites = "Favorites"
key_items = "Key Items"
medicine = "Medicine"
poke_balls = "Poké Balls"
battle_items = "Battle Items"
tms = "TMs & HMs"
berries = "Berries"
other_items = "Other Items"

[names.items]
poke_ball = "Poké Ball"
great_ball = "Great Ball"
ultra_ball = "Ultra Ball"
master_ball = "Master Ball"
net_ball = "Net Ball"
dive_ball = "Dive Ball"
nest_ball = "Nest Ball"
repeat_ball = "Repeat Ball"
timer_ball = "Timer Ball"
luxury_ball = "Luxury Ball"
premier_ball = "Premier Ball"
dusk_ball = "Dusk Ball"
heal_ball = "Heal Ball"
quick_ball = "Quick Ball"
cherish_ball = "Cherish Ball"
