[names.maps]
test-map-1 = "Test Map 1"
test-map-2 = "Test Map 2"
test-map-3 = "Test Map 3"
test-pc = "Test PC"

[names.bag]
items = "Items"
medicine = "Medicine"
pokeballs = "Poké Balls"
tms = "TMs & HMs"
berries = "Berries"
mail = "Mail"
battle_items = "Battle Items"
key_items = "Key Items"
