local_name = "English (United States)"
english_name = "English (United States)"
author = "Kaisadilla"
version = "1.0"

yes = "Yes"
no = "No"
on = "On"
off = "Off"

menu.pokedex = "Pokédex"
menu.pokemon = "Pokémon"
menu.bag = "Bag"
menu.player = "{player}"
menu.save = "Save"
menu.options = "Options"
menu.debug = "Debug"
menu.exit = "Exit"

screens.save.text.1 = "Would you like to save the game? This will replace the current save for this game."
screens.save.text.2 = "{player} saved the game."

screens.bag.close = "<close bag>"
screens.bag.item_menu.give = "Give"
screens.bag.item_menu.toss = "Toss"
screens.bag.item_menu.cancel = "Cancel"

screens.options.title = "Options"
screens.options.close = "<close>"
screens.options.labels.screen_size = "Screen size"
screens.options.labels.music_volume = "Music volume"
screens.options.labels.sound_volume = "Sound volume"
screens.options.labels.text_speed = "Text speed"
screens.options.labels.battle_animations = "Battle animations"
screens.options.labels.give_nicknames = "Give nicknames"
screens.options.labels.message_frame = "Message frame"
screens.options.labels.menu_frame = "Menu frame"
screens.options.labels.font = "Font"
screens.options.desc.screen_size = "The scale of the pixels in the game's screen."
screens.options.desc.music_volume = "The volume of background music and ambient."
screens.options.desc.sound_volume = "The volume of sound effects."
screens.options.desc.text_speed = "The speed at which text appears."
screens.options.desc.battle_animations = "Whether to play the animations of moves in battles."
screens.options.desc.give_nicknames = "Whether to ask for a nickname when you capture a Pokémon. You can still give them a nickname afterwards."
screens.options.desc.message_frame = "The appearance of dialogue boxes."
screens.options.desc.menu_frame = "The appearance of other kind of boxes."
screens.options.desc.font = "The font used by the game."
screens.options.screen_size.1x = "1x"
screens.options.screen_size.2x = "2x"
screens.options.screen_size.3x = "3x"
screens.options.screen_size.4x = "4x"
screens.options.screen_size.full = "Full"
screens.options.text_speed.slow = "Slow"
screens.options.text_speed.mid = "Mid"
screens.options.text_speed.fast = "Fast"
screens.options.text_speed.instant = "Instant"
screens.options.message_frames.current = "Type {%0}/{%1}"
screens.options.box_frames.current = "Type {%0}/{%1}"

ui.scoreboard.money.label = "Money"
ui.scoreboard.money.value = "$ {money}"

ui.shop.cancel = "<cancel>"
ui.shop.buy_how_many = "{%0}? Certainly.\nHow many would you like?"
ui.shop.buy_confirm = "{%0}, and you want {%1}. That will be ${%2}, is that OK?"
ui.shop.buy_complete = "Here you are!\nThank you!"
ui.shop.not_enough_money = "You don't have enough money."
ui.shop.sell_how_many = "{%0}?\nHow many would you like to sell?"
ui.shop.sell_confirm = "I can pay ${%0}.\nWould that be ok?"
ui.shop.sell_complete = "Turned over the {%0} and received ${%1}."
