[descriptions.items]
poke_ball = "A device for catching wild Pokémon. It's thrown like a ball at a Pokémon, comfortably encapsulating its target."
great_ball = "A good, high-performance Poké Ball that provides a higher success rate for catching Pokémon than a standard Poké Ball."
ultra_ball = "An ultra-high performance Poké Ball that provides a higher success rate for catching Pokémon than a Great Ball."
master_ball = "The very best Poké Ball with the ultimate level of performance. With it, you will catch any wild Pokémon without fail."
net_ball = "A somewhat different Poké Ball that is more effective when catching Water- or Bug-type Pokémon."
dive_ball = "A somewhat different Poké Ball that is more effective when catching Pokémon in or on the water."
nest_ball = "A somewhat different Poké Ball that becomes more effective the lower the level of the wild Pokémon."
repeat_ball = "A somewhat different Poké Ball that is more effective when catching a Pokémon of a species that you've caught before."
timer_ball = "A somewhat different Poké Ball that becomes more effective at catching Pokémon the more turns that are taken in battle."
luxury_ball = "A particularly comfortable Poké Ball that makes a wild Pokémon quickly grow friendlier after being caught."
premier_ball = "A somewhat rare Poké Ball made to commemorate a special occasion of some sort."
dusk_ball = "A somewhat different Poké Ball that is more effective when catching Pokémon at night or in dark places, such as caves."
heal_ball = "A remedial Poké Ball that restores HP and eliminates status conditions for a Pokémon caught with it."
quick_ball = "A somewhat different Poké Ball that is more effective at catching Pokémon when used first thing in a battle."
cherish_ball = "A quite rare Poké Ball made to commemorate a special occasion of some sort."
